### ISSUE TITLE
[BUG] Drag tab bug of `#close-confirmation : Show confirmation with multiple windows`

### ISSUE THREAD

**Issue by Unknown78** [Alex313031/Thorium-Win#240]
## Backgrounds
 - OS: Windows 11
 - Thorium Version: [Thorium_SSE3_124.0.6367.218.zip](https://github.com/Alex313031/Thorium-Win/releases/tag/M124.0.6367.218)

## Problems

Descriptions of the flag:

> Close Confirmation
> Show a warning prompt when closing browser window(s). – Mac, Windows, Linux, ChromeOS, Fuchsia, Lacros
> 
> `#close-confirmation`

Settings of it:

> - Default
> - Show confirmation with last window
> - Show confirmation with multiple windows

If I drag a tab into an existing window, then it will create a new hidden window such that it will prompt close confirmation even though I only have one window. If I close that window, then the Thorium Task Manager will remains instead of closing. If I close it, then Windows Task Manager will show that Thorium processes is still exists and not stopped.

See the .gif below
![bugs](https://github.com/user-attachments/assets/ec1d85ae-4409-4d8e-9c38-7092cb0de4dc)

**Comment by gz83** [comment]
Please check 'Continue running background apps when Chromium is closed' option status

**Comment by Unknown78** [comment]
@gz83 v128 still has the same bug

**Comment by Unknown78** [comment]
@gz83 @Alex313031 

https://github.com/Alex313031/Thorium-Win/releases/tag/M130.0.6723.174
I've just tried it with `Thorium_SSE4_130.0.6723.174.zip` and `Thorium_SSE3_130.0.6723.174.zip`

The release notes states that:
> Close confirmation flag fixed.

But now instead of the buggy behavior above, the browser crashed If I drag a tab into an existing window.

**Comment by gz83** [comment]
I can reproduce this issue and will pass it on to Alex to follow up

@Alex313031 



> [@gz83](https://github.com/gz83) [@Alex313031](https://github.com/Alex313031)
> 
> https://github.com/Alex313031/Thorium-Win/releases/tag/M130.0.6723.174 I've just tried it with `Thorium_SSE4_130.0.6723.174.zip` and `Thorium_SSE3_130.0.6723.174.zip`
> 
> The release notes states that:
> 
> > Close confirmation flag fixed.
> 
> But now instead of the buggy behavior above, the browser crashed If I drag a tab into an existing window.

**Comment by Alex313031** [comment]
@gz83 @Unknown78 Dang. OK I guess I fixed the original issue, but now there is a new one.

**Comment by Unknown78** [comment]
@gz83 It still crashes with [thorium_SSE4_138.0.7204.300.zip](https://github.com/Alex313031/Thorium-Win/releases/tag/M138.0.7204.300)

**Comment by gz83** [comment]
@Alex313031 Please check if there are any problems during the rebasing process.

**Comment by Unknown78** [comment]
@gz83 It still crashes with [Thorium_SSE4_144.0.7559.254.zip ](https://github.com/gz83/thorium/releases/tag/M144.0.7559.254)

**Comment by gz83** [comment]
@Unknown78 

Thanks for the feedback; I'll take a look at it later. I'm currently busy fixing the Android build.

**Comment by gz83** [comment]
The crash has been fixed in this commit, and the fix will be included in the next update.

https://github.com/gz83/thorium/commit/abc2f1a65934b26c10dce4f67b222ab23d4d3282

**Comment by Unknown78** [comment]
```cpp
      tab_strip_model_delegate_->AddTabAt(GURL(), -1, true);
```
@gz83 Is this the one that causes crash? Why?

I thought it is only `Thorium`, but `Ungoogled Chromium` also has the same issue. 
https://github.com/ungoogled-software/ungoogled-chromium/issues/3397

That's weird.

**Comment by gz83** [comment]
Yes, this is the same problem that ungoogled chromium encountered, and thorium obtained this patch from ungoogled chromium.

@Unknown78

**Comment by Unknown78** [comment]
So you and Alex were working to fix the upstream patch?
That's beyond the call of duty lol

**Comment by gz83** [comment]
Please try the M150 version and see if you still encounter this issue.

https://github.com/gz83/thorium/releases/tag/M150.0.7871.47

**Comment by Unknown78** [comment]
@gz83 The issue is fixed, good job!
